version: 1
disable_existing_loggers: False

formatters:
  verbose:
    format: '[eduzen_bot] %(asctime)s: %(levelname)s %(message)s'
  colored:
      (): structlog.stdlib.ProcessorFormatter,
      processor: structlog.dev.ConsoleRenderer(colors=True)
handlers:
  stdout:
    class: logging.StreamHandler
    stream: 'ext://sys.stdout'
    formatter: colored
    level: DEBUG

  file:
    class: logging.handlers.RotatingFileHandler
    filename: "eduzen_bot.log"
    formatter: verbose
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
    level: INFO
root:
  'handlers': [file]
  'propagate': True
